### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by tonjelund** [Skatteetaten/dsop-account-consumer-contract#10]
Hi

Under Test cases -> 200 scenario (https://github.com/Skatteetaten/dsop-account-consumer-contract), the explanation under "Interaction" should be:

Test state | Interaction
-- | --
test GET AccountList | Sends an AccountList request with PartyID: 909716212
test GET AccountDetails | Sends an AccountDetails request for a given accountReference
test GET Roles | Sends a Roles request for a given accountReference
test GET Cards | Sends a Cards request for a given accountReference
test GET Transactions | Sends a Transaction request for a given accountReference

PACT should also be updated to the new version of the API's - version 1.1.  API spek V.1.1: https://bitsnorge.github.io/dsop-accounts-api-v1p1/ 

/Tonje Falch Lund

**Comment by adrianSoria** [comment]
Yes @tonjelund . Jeg skal se på det :)
