### ISSUE TITLE
etat_consumer-bank_provider.json

### ISSUE THREAD

**Issue by thorejoa** [Skatteetaten/dsop-account-consumer-contract#7]
Hei,

Stemmer det at accountReference oppgitt i "path" (https://github.com/Skatteetaten/dsop-account-consumer-contract/blob/master/src/test/resources/pacts/etat_consumer-bank_provider.json#L13) er feil?

Kan dere evt. oppdatere det med MFQ9dT2XYx8_aTNftDCtMbvZacI__3VVyM9ZZBOo4_Zr istedenfor 5687123451?

**Comment by adrianSoria** [comment]
Jeg tar en titt på det

**Comment by adrianSoria** [comment]
Nå skal det være løst.
